# MALMEN: Fast Model Editing at Scale
# Paper: https://arxiv.org/abs/2304.00740

defaults:
  - edit/base_editor@_here_
  - _self_

handler: MALMENEditor

method_args:
  layers: [5, 6, 7, 8]
  archive: null
  edit_lr: 1.0e-4
  n_hidden: 256
  rank: 1920
  batch_size: 10
  n_edits: 50
  lambda_reg: 1.0e-3
