model_args:
  pretrained_model_name_or_path: "baichuan-inc/Baichuan2-13B-Chat"
  torch_dtype: bfloat16
  trust_remote_code: true
tokenizer_args:
  pretrained_model_name_or_path: "baichuan-inc/Baichuan2-13B-Chat"
  trust_remote_code: true
template_args:
  apply_chat_template: true
  user_start_tag: "<reserved_106>"
  user_end_tag: ""
  asst_start_tag: "<reserved_107>"
  asst_end_tag: ""
