model_args:
  pretrained_model_name_or_path: "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B"
  attn_implementation: 'flash_attention_2'
  torch_dtype: bfloat16
tokenizer_args:
  pretrained_model_name_or_path: "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B"
template_args:
  apply_chat_template: true
  system_prompt: "You are a helpful assistant."
  user_start_tag: "<|User|>"
  user_end_tag: ""
  asst_start_tag: "<|Assistant|>"
  asst_end_tag: "<|end▁of▁sentence|>"
