model_args:
  pretrained_model_name_or_path: "THUDM/glm-4-9b-chat"
  torch_dtype: bfloat16
  trust_remote_code: true
tokenizer_args:
  pretrained_model_name_or_path: "THUDM/glm-4-9b-chat"
  trust_remote_code: true
template_args:
  apply_chat_template: true
  system_prompt: "You are a helpful assistant."
  user_start_tag: "<|user|>\n"
  user_end_tag: ""
  asst_start_tag: "<|assistant|>\n"
  asst_end_tag: ""
