model_args:
  pretrained_model_name_or_path: "01-ai/Yi-1.5-9B-Chat"
  attn_implementation: 'flash_attention_2'
  torch_dtype: bfloat16
tokenizer_args:
  pretrained_model_name_or_path: "01-ai/Yi-1.5-9B-Chat"
template_args:
  apply_chat_template: true
  user_start_tag: "<|im_start|>user\n"
  user_end_tag: "<|im_end|>\n"
  asst_start_tag: "<|im_start|>assistant\n"
  asst_end_tag: "<|im_end|>\n"
